app = "gxktm-web-app"
primary_region = "ord"

[build]
  dockerfile = "Dockerfile"

[build.args]
  NEXT_PUBLIC_SUPABASE_URL = "https://zncgxjgxbvzwdukgatnn.supabase.co"
  NEXT_PUBLIC_SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpuY2d4amd4YnZ6d2R1a2dhdG5uIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjY5NTc5MDcsImV4cCI6MjA4MjUzMzkwN30.AEXvMW_GI4fZ3V_o6rFfo5HLGUDcWnOlCP-hamTbgpU"
  NEXT_PUBLIC_CONTACT_EMAIL = "vince.trinh80@gmail.com"
  NEXT_PUBLIC_HOME_URL = "gxktm.org"
  NEXT_PUBLIC_API_URL = "https://gxktm-backend.fly.dev"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = "stop"
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]

[http_service.concurrency]
  type = "requests"
  hard_limit = 250
  soft_limit = 200

[[vm]]
  size = "shared-cpu-1x"
  memory = "512mb"
