app = "gxktm_frontend" # Change this to your desired globally unique app name
primary_region = "ord"

[build]
  dockerfile = "Dockerfile" # Adjust path if your Dockerfile is named differently

[http_service]
  internal_port = 3000 # The port your frontend container exposes (e.g., 3000 for Next.js/React)
  force_https = true
  auto_stop_machines = "off"
  auto_start_machines = false
  min_machines_running = 1
  processes = ["app"]

[http_service.concurrency]
  type = "requests"
  hard_limit = 250
  soft_limit = 200