app = "gxktm-web-app"
primary_region = "ord"

[build]
  dockerfile = "Dockerfile"

[build.args]
  NEXT_PUBLIC_SUPABASE_URL = "https://pwrytxembgahkazydrac.supabase.co"
  NEXT_PUBLIC_SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InB3cnl0eGVtYmdhaGthenlkcmFjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzczOTk1ODYsImV4cCI6MjA5Mjk3NTU4Nn0.5ZmbabHW1g8SyDMwK0_TYrhIVExm2HaqxD8S8GH63xs"
  NEXT_PUBLIC_CONTACT_EMAIL = "Theresanganbl@gmail.com"
  NEXT_PUBLIC_HOME_URL = "gxktm.org"
  NEXT_PUBLIC_API_URL = "https://gxktm-backend.fly.dev"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = "stop"
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]

[http_service.concurrency]
  type = "requests"
  hard_limit = 250
  soft_limit = 200

[[vm]]
  size = "shared-cpu-1x"
  memory = "512mb"
